export const enum Etat {
  DISPO_BASE_OP = 'DISPO_BASE_OP',

  DISPO_HORS_BASE_OP = 'DISPO_HORS_BASE_OP',

  ATTENTE_INTERVENTION = 'ATTENTE_INTERVENTION',

  INDISPO_EN_INTERVENTION = 'INDISPO_EN_INTERVENTION',

  INDISPO_AUTRES = 'INDISPO_AUTRES',
}
